# Frontend Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json /app/package.json
RUN npm install --silent
COPY frontend /app
RUN npm run build
EXPOSE 5173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
