version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:8000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:8000/auth/google/callback
      - DATABASE_URL=sqlite:///db/app.db
    volumes:
      - ./db:/app/db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
